### ISSUE TITLE
EchoID needed in JSON card object 

### ISSUE THREAD

**Issue by ardeay** [EchoMTG/mtg-csv-reader#3]
https://github.com/ardeay/mtg-csv-reader/blob/6b2adf0e754d7ea73e8be5fc73a6afc3f6d1577e/src/helpers/card_parser.ts#L52

Added the EchoID of the card found here https://dev.echomtg.com/api/data/lookup/, that needed to insert a card into the api from the import interface. 

Its absent:
![image](https://user-images.githubusercontent.com/729972/72782128-d671a180-3bd7-11ea-8920-a8998148e8d2.png)

**Comment by ardeay** [comment]
I see you are adding it here https://github.com/ardeay/mtg-csv-reader/blob/6b2adf0e754d7ea73e8be5fc73a6afc3f6d1577e/src/helpers/card_parser.ts#L237

But when testing with https://github.com/ardeay/mtg-csv-reader/blob/master/example_datasets/basic_csv_with_many_cards.csv I get the above resolves with no EchoID

**Comment by Jed-Giblin** [comment]
If you test with the most recent version 975e4aa939f06fe34059b777a3cf0187c0b48788, the code will put that card in the errors list because the provided row has MIR as a set and Mirrodin as a set name which is a mismatch. Do we want to support checking for correctness in both? Right now, we have a higher priority on set_code

You can always local test with `RUN_LOCAL=1 npm run dev`

**Comment by ardeay** [comment]
@Jed-Giblin i need to see how to deploy and run firebase locally. I have only run cloud functions. 

Could you add info on that to read me, how to deploy our app and a link to running local

**Comment by ardeay** [comment]
I'll be adding a dropdown for a user to switch their setname in the errors table, this will allow them to clean data retrying the unread bad data
